### ISSUE TITLE
Dock icon is a bit large

### ISSUE THREAD

**Issue by jlongrc** [chenasraf/gInbox#15]
This isn't the most pressing issue, but the dock icon seems to me like it is wider than all of my other dock icons. Of course, some of that has to do with the logo having a wider aspect ratio than most icons. This might be an easy fix by scaling down, though.

![screen shot 2014-11-13 at 1 31 05 pm](https://cloud.githubusercontent.com/assets/4957401/5034052/5af9a1c0-6b39-11e4-8f0f-0600e8696ca7.png)

**Comment by chenasraf** [comment]
Closing in favor of #28
