### ISSUE TITLE
Clarify license for users

### ISSUE THREAD

**Issue by cgruber** [chenasraf/gInbox#31]
Please clarify the terms under which you are distributing this software, and making it available.  At present all of the files are listed with a copyright and no license grant, and downloads do not include any information about grants of license.  It literally means that no one has the right to us this software without your permission, but there is nowhere that indicates that anyone has such permission. 

Please clarify this, so that folks can download without fear of legal risk.

**Comment by chenasraf** [comment]
https://github.com/chenasraf/gInbox/blob/master/README.md
