### ISSUE TITLE
gInbox does not start on OSX

### ISSUE THREAD

**Issue by facundofarias** [chenasraf/gInbox#33]
I am using an iMac with OSX 10.9.5. It simply does not start at all, take a look: 

![image](https://cloud.githubusercontent.com/assets/2700564/6602349/786b48aa-c81b-11e4-846a-ce6a82506898.png)

Thanks!

**Comment by facundofarias** [comment]
Adding process info.
![image](https://cloud.githubusercontent.com/assets/2700564/6602428/e6d8c1c8-c81b-11e4-8e39-10bae419c718.png)

**Comment by chenasraf** [comment]
Duplicate of #24
