### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by bilby91** [chenasraf/gInbox#35]
Any update on OS X Notifications for new email ? 

Is there any branch with WIP ?

**Comment by chenasraf** [comment]
I'm currently rewriting the app to work better, find leaks, etc. once that's stable I'll be working on this. Sorry for the slow progression... :( time is dear

**Comment by Zianwar** [comment]
+1

**Comment by saadel** [comment]
+1

**Comment by mrpunkin** [comment]
+1

**Comment by thomasw** [comment]
+1

**Comment by yomybaby** [comment]
+1 please!

**Comment by erik-coddut** [comment]
+1

**Comment by gerald-coddut** [comment]
Can I have a +1,  :+1: and +:one: please, amen!

**Comment by rtblair** [comment]
+1

**Comment by jendas1** [comment]
+1
