### ISSUE TITLE
Full-screen mode

### ISSUE THREAD

**Issue by ssthormess** [chenasraf/gInbox#43]
Hi,

Currently it is not possible to maximize the app to cover the entire screen including the menu bar space, as if it was a separated space. Maybe this integration to OSX can be added in the future?

**Comment by maximkulkin** [comment]
Looks like it is already supported on latest master

**Comment by bilby91** [comment]
Yes, 2bc6329bb2ef4e03d5cbc56f8096f27ff6a6aa9f adds support for this.

**Comment by wjramos** [comment]
This issue should be closed if the feature has been integrated
