### ISSUE TITLE
Can’t use Multiple Accounts

### ISSUE THREAD

**Issue by tjdraper** [chenasraf/gInbox#48]
I’ve been looking for an app that would let me use Inbox separately from my browser. One problem I’ve run into is that I have three accounts. The app seems to see that I’m already logged in to the first one. But when I click the corner icon to switch to a different account, it opens the window in my default browser. It would be great if we could have tabs for multiple accounts.

**Comment by chenasraf** [comment]
It's in the source now. Not compiled yet (dup of #30)
